apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: platform-create-pods
  namespace: {{ .Release.Namespace }}
subjects:
  - kind: User
    name: "system:serviceaccount:{{ .Release.Namespace }}:{{ include "datacater.serviceAccountName" . }}"
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name:  datacater-pod-creater
  apiGroup: rbac.authorization.k8s.io
