apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: datacater-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: {{ .Values.gcp.addressName }}
    kubernetes.io/ingress.class: {{ .Values.gcp.ingressClass }}
    {{- if .Values.gcp.managedCertName }}
    kubernetes.io/ingress.allow-http: "false"
    networking.gke.io/managed-certificates: {{ .Values.gcp.managedCertName }}
    {{- else }}
    kubernetes.io/ingress.allow-http: "true"
    {{ end }}
spec:
  defaultBackend:
    service:
      name: platform-service
      port:
        number: 80
