apiVersion: v1
kind: Service
metadata:
  name: platform-service
  labels:
    app: datacater-platform
  annotations:
    cloud.google.com/backend-config: '{"ports": {"443":"platform-timeout"}}'
    cloud.google.com/neg: '{"ingress": true}'
spec:
  selector:
    app: datacater-platform
  type: {{ .Values.platform.serviceType }}
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http

