{{ range  $index, $value := .Values.gcp.standaloneCloudSqlProxy -}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-sql-proxy-{{ $index }}
  labels:
    app: cloud-sql-proxy-{{ $index }}
spec:
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: cloud-sql-proxy-{{ $index }}
  template:
    metadata:
      labels:
        app: cloud-sql-proxy-{{ $index }}
    spec:
      serviceAccountName: datacater-main
      restartPolicy: Always
      volumes:
        - name: google-cloudsql-key
          secret:
            secretName: {{ $value.cloudSqlKey }}
      containers:
        - name: cloud-sql-proxy
          image: "gcr.io/cloudsql-docker/gce-proxy:{{- $.Values.gcp.cloudSqlProxyVersion -}}"
          ports:
            - containerPort: {{ $value.targetPort }}
          command:
            - "/cloud_sql_proxy"
            - "-instances={{ $value.cloudSqlInstance }}=tcp:0.0.0.0:{{ $value.targetPort }}"
            - "-credential_file=/secrets/key.json"
          securityContext:
            runAsNonRoot: true
          volumeMounts:
            - mountPath: /secrets/
              name: google-cloudsql-key
              readOnly: true
{{ end -}}
