{{ range $index, $value := .Values.gcp.standaloneCloudSqlProxy -}}
---
apiVersion: v1
kind: Service
metadata:
  name: cloud-sql-proxy-{{ $index }}
  labels:
    app: cloud-sql-proxy-{{ $index }}
spec:
  selector:
    app: cloud-sql-proxy-{{ $index }}
  type: ClusterIP
  ports:
    - port: 80
      targetPort: {{ $value.targetPort }}
      protocol: TCP
      name: http
{{ end -}}
