datacater:
  publicDomainName: datacater.example.com
  # Elastic Container Registyr is used for storing pipeline images.
  # pipelineRegistry: $account_id.dkr.ecr.$region.amazonaws.com
  pipelineRegistry: 193290265706.dkr.ecr.eu-central-1.amazonaws.com
  kafka:
    replicas: 3
    resources:
      requests:
        cpu: 0.5
        memory: 6Gi
      limits:
        memory: 6Gi
  connect:
    replicas: 2
    resources:
      requests:
        cpu: 0.5
        memory: 6Gi
      limits:
        memory: 6Gi

platform:
  envConfigMap:
    # DataCater uses this mail for the FROM field
    dataCaterMailerFrom: no-reply@example.com
    dataCaterDefaultUser: admin@example.com
