# GCP related settings
gcp:
  # Used by cloud-sql proxy for targeting the right cloud-sql instance
  # Format is $PROJECT_ID:$REGION:$INSTANCE_NAME
  cloudSqlInstance:
  # GCP static ip address name for datacater to keep fixed ip's on new deployments
  addressName: datacater-gcp-ip

datacater:
  # Used for Google Cloud ManagedCert and From field in mails.
  publicDomainName: datacater.example.com
  # GCR used for storing pipeline images follows $GEO.gcr.io/$PROJECT_ID/$PIPELINE_REGISTRY
  pipelineRegistry: eu.gcr.io/example-project-id/pipeline-registry
  kafka:
    replicas: 3
    resources:
      requests:
        cpu: 0.5
        memory: 6Gi
      limits:
        memory: 6Gi
  connect:
    replicas: 2
    resources:
      requests:
        cpu: 0.5
        memory: 6Gi
      limits:
        memory: 6Gi

platform:
  envConfigMap:
    # DataCater uses this mail for the FROM field
    dataCaterMailerFrom: no-reply@example.com
    dataCaterDefaultUser: admin@example.com
