apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: datacater
  {{- with .Values.datacater.kafka.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  kafka:
    resources:
      {{- toYaml .Values.datacater.kafka.resources | nindent 6 }}
    version: 3.2.3
    replicas: {{ .Values.datacater.kafka.replicas }}
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      log.message.format.version: "3.2"
      inter.broker.protocol.version: "3.2"
      message.max.bytes: "3145728"
      replica.fetch.max.bytes: "3145728"
    storage:
      type: persistent-claim
      size: 500Gi
    template:
      pod:
        affinity:
          {{- toYaml .Values.datacater.kafka.affinity | nindent 10 }}
        metadata:  
          {{- with .Values.datacater.kafka.annotations }}
          annotations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
  zookeeper:
    replicas: 3
    storage:
      type: persistent-claim
      size: 20Gi
    resources:
      {{- toYaml .Values.datacater.zookeeper.resources | nindent 6 }}
    template:
      pod:
        affinity:
          {{- toYaml .Values.datacater.zookeeper.affinity | nindent 10 }}
        metadata:  
          {{- with .Values.datacater.zookeeper.annotations }}
          annotations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
  entityOperator:
    template:
      pod:
        affinity:
          {{- toYaml .Values.datacater.entityOperator.affinity | nindent 10 }}
        metadata:
          {{- with .Values.datacater.entityOperator.annotations }}
          annotations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
    topicOperator: 
      resources:
        {{- toYaml .Values.datacater.entityOperator.topicOperator.resources | nindent 8 }}
    userOperator: 
      resources:
        {{- toYaml .Values.datacater.entityOperator.userOperator.resources | nindent 8 }}