apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnect
metadata:
  name: datacater
  {{- with .Values.datacater.connect.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  version: 3.2.3
  resources:
    {{- toYaml .Values.datacater.connect.resources | nindent 4 }}
  replicas: {{ .Values.datacater.connect.replicas }}
  bootstrapServers: datacater-kafka-bootstrap:9093
  livenessProbe:
    initialDelaySeconds: 120
    timeoutSeconds: 120
  readinessProbe:
    initialDelaySeconds: 120
    timeoutSeconds: 120
  image: images.datacater.io/datacater/strimzi-kafka:0.25.0-kafka-2.8.0-20220216
  tls:
    trustedCertificates:
      - secretName: datacater-cluster-ca-cert
        certificate: ca.crt
  config:
    group.id: datacater-connect-cluster
    offset.storage.topic: datacater_connect_offsets
    config.storage.topic: datacater_connect_configs
    status.storage.topic: datacater_connect_statuses
    config.storage.replication.factor: -1
    offset.storage.replication.factor: -1
    status.storage.replication.factor: -1
    connector.client.config.override.policy: "All"
    producer.max.request.size: "3145728"
    consumer.fetch.message.max.bytes: "3145728"
  template:
    pod:
      imagePullSecrets:
        - name: datacater
      affinity:
        {{- toYaml .Values.datacater.kafka.affinity | nindent 8 }}
      metadata:
        {{- with .Values.datacater.connect.annotations }}
        annotations:
          {{- toYaml . | nindent 10 }}
        {{- end }}
