{{ if .Values.gcp.managedCertName -}}
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: {{ .Values.gcp.managedCertName }}
spec:
  domains:
    - {{ trimPrefix "https://" .Values.datacater.publicDomainName }}
{{ end -}}
