apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: datacater-ingress
  {{- with .Values.datacater.ingressAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  defaultBackend:
    service:
      name: platform-service
      port:
        number: 80
