apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: datacater-ingress
  annotations:
    # TODO change to accordingly
    kubernetes.io/ingress.class: "default"
spec:
  defaultBackend:
    service:
      name: platform-service
      port:
        number: 80
