---
apiVersion: v1
kind: Secret
metadata:
  name: datacater-mailer
  labels:
    app.kubernetes.io/name: datacater
type: Opaque
stringData:
  MAILER_HOST: {{ .Values.datacater.mail.host | quote }}
  MAILER_PASSWORD: {{ .Values.datacater.mail.password | quote }}
  MAILER_PORT: {{ .Values.datacater.mail.port | quote }}
  MAILER_USER: {{ .Values.datacater.mail.user | quote }}
  MAILER_TLS: {{ .Values.datacater.mail.tls | quote }}
  MAILER_SSL: {{ .Values.datacater.mail.ssl | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: datacater-db-secret
  labels:
    app.kubernetes.io/name: datacater
type: Opaque
stringData:
  PG_HOST: {{ .Values.datacater.postgres.host | quote }}
  PG_PORT: {{ .Values.datacater.postgres.port | quote }}
  PG_USER: {{ .Values.datacater.postgres.user | quote }}
  PG_PASSWORD: {{ .Values.datacater.postgres.password | quote }}
  PG_DATABASE_NAME: {{ .Values.datacater.postgres.database | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: datacater-docker
  labels:
    app.kubernetes.io/instance: datacater
type: Opaque
stringData:
  docker_registry_user: {{ .Values.datacater.docker.user | quote }}
  docker_registry_password: {{ .Values.datacater.docker.password | quote }}
  docker_registry_uri: {{ .Values.datacater.docker.uri | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: datacater
  labels:
    app.kubernetes.io/name: datacater
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "datacater.registry.imagePullSecret" . }}
---
apiVersion: v1
kind: Secret
metadata:
  name: pipeline-registry
  labels:
    app.kubernetes.io/name: datacater
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "datacater.pipeline.imagePullSecret" . }}
