apiVersion: v1
kind: Service
metadata:
  name: platform-service
  labels:
    app: datacater-platform
spec:
  selector:
    app: datacater-platform
  type: {{ .Values.platform.serviceType }}
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http

